// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4MGcmbBt71YZgZDHfeyuOQVY9QztwzQ',
    appId: '1:596667116068:web:8af351591ac00bd01dc6b1',
    messagingSenderId: '596667116068',
    projectId: 'mithaq-956c5',
    authDomain: 'mithaq-956c5.firebaseapp.com',
    storageBucket: 'mithaq-956c5.firebasestorage.app',
    measurementId: 'G-B7EK2BVVXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyaR8eY9HxgbdHeQV3HggleJx0DW6fe2E',
    appId: '1:596667116068:android:b9813edb0237dfb51dc6b1',
    messagingSenderId: '596667116068',
    projectId: 'mithaq-956c5',
    storageBucket: 'mithaq-956c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkfQH68Qtz95v3vJqLD-RQsgY-Vic6wZo',
    appId: '1:596667116068:ios:3195bfedb980cc801dc6b1',
    messagingSenderId: '596667116068',
    projectId: 'mithaq-956c5',
    storageBucket: 'mithaq-956c5.firebasestorage.app',
    iosBundleId: 'com.example.complaintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkfQH68Qtz95v3vJqLD-RQsgY-Vic6wZo',
    appId: '1:596667116068:ios:3195bfedb980cc801dc6b1',
    messagingSenderId: '596667116068',
    projectId: 'mithaq-956c5',
    storageBucket: 'mithaq-956c5.firebasestorage.app',
    iosBundleId: 'com.example.complaintApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP4MGcmbBt71YZgZDHfeyuOQVY9QztwzQ',
    appId: '1:596667116068:web:7fa8cdc711b1e75c1dc6b1',
    messagingSenderId: '596667116068',
    projectId: 'mithaq-956c5',
    authDomain: 'mithaq-956c5.firebaseapp.com',
    storageBucket: 'mithaq-956c5.firebasestorage.app',
    measurementId: 'G-DR6P0VFCM6',
  );
}
